BASIC_TOKENS = {
    ")": "RIGHT_PAREN",
    "(": "LEFT_PAREN",
    "}": "RIGHT_BRACE",
    "{": "LEFT_BRACE",
    ".": "DOT",
    ",": "COMMA",
    ";": "SEMICOLON",
    "+": "PLUS",
    "-": "MINUS",
    "*": "STAR",
    "==": "EQUAL_EQUAL",
    "=": "EQUAL",
    "!=": "BANG_EQUAL",
    "!": "BANG",
    "<=": "LESS_EQUAL",
    ">=": "GREATER_EQUAL",
    "<": "LESS",
    ">": "GREATER",
    "/": "SLASH",
}
SPECIAL_REGEX = "().+*"

RESERVED_WORDS = [
    "and",
    "class",
    "else",
    "false",
    "for",
    "fun",
    "if",
    "nil",
    "or",
    "print",
    "return",
    "super",
    "this",
    "true",
    "var",
    "while",
]
